### PR TITLE
Fix tile on the corner

### PR DESCRIPTION
**Pull request by perebartrolisimo**
We had still issues with the tile in the corner. After the fix the tile was smaller and the resolution was bad. We this small fix we get correct size and resolution of the tile in the corner.

### CODE REVIEW

**Comment by ruven** [comment]
What IIIF server are you using for this? iipsrv? If so, which version?

**Comment by perebartrolisimo** [comment]
We use iipsrv version 1.2. We run the latest version from docker iipsrv/iipsrv.

**Comment by ruven** [comment]
OK. In fact this fix is needed because there is a bug in the size calculation for these edge cases in iipsrv version 1.2. Basically, there is a mis-match between the IIIF region part of the request and the size, which confuses things. This is fixed in the latest development version of iipsrv.

Your patch also just needs modifying slightly, as the height needs to be calculated in the same way as the width.

By the way, if you are only using iipmooviewer with the iipsrv server, I would recommend you just use the default IIP API and not IIIF as requests will be slightly faster. The server will still of course still handle IIIF requests for other viewers etc.

**Comment by perebartrolisimo** [comment]
Thank you for your reply. I'll will check the latest update since I agree that it might have been a bug in the server, according to IIIF specification. 

Thanks for the suggestion of using IIP instead of IIIF, however our customer wants to have IIIF, so we will stick to it. 

Best Regards Pere

**Pull request merged**
